export { default as LoginForm } from './Login'
export { default as RegisterForm } from './Register'
export { default as AddCategory } from './AddCategory'
export { default as EditCategory } from './EditCategory'
export { default as HomePage } from './HomePage'
export { default as ProfilePage } from './ProfilePage'