export { default as LoginForm } from './Login'
export { default as RegisterForm } from './Register'
export { default as AddCategory } from './CreateTask'
export { default as EditCategory } from './EditTask'
export { default as HomePage } from './Home'
export { default as ProfilePage } from './ProfilePage'